# Generated by Django 3.2.9 on 2022-01-08 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='cost_price',
            field=models.DecimalField(decimal_places=0, max_digits=7, null=True, verbose_name='Cost Price'),
        ),
        migrations.AlterField(
            model_name='products',
            name='selling_price',
            field=models.DecimalField(decimal_places=0, max_digits=7, null=True, verbose_name='Selling Price'),
        ),
    ]
