# Generated by Django 3.2.9 on 2022-03-22 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_auto_20220316_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='created_at',
            field=models.DateField(verbose_name='Date'),
        ),
    ]
