# Generated by Django 3.2.9 on 2022-01-08 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Salary',
        ),
    ]
