# Generated by Django 3.2.9 on 2022-01-08 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0002_delete_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
