# Generated by Django 3.2.9 on 2022-01-08 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0003_alter_employee_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
