# Generated by Django 3.2.9 on 2022-01-24 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_currency', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('dollars', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
