# Generated by Django 3.2.9 on 2022-03-22 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rate', '0002_auto_20220316_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='created_at',
            field=models.DateField(verbose_name='Date'),
        ),
    ]
