# Generated by Django 3.2.9 on 2022-01-08 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventories',
            name='selling_price',
        ),
    ]
