# Generated by Django 3.2.9 on 2022-02-24 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventories',
            name='numberPlate',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.CreateModel(
            name='TruckExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10, null=True)),
                ('Truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.inventories')),
            ],
        ),
    ]
