# Generated by Django 3.2.9 on 2022-01-08 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_remove_inventories_selling_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventories',
            name='cost_price',
            field=models.DecimalField(decimal_places=0, max_digits=7, null=True, verbose_name='Cost Price'),
        ),
    ]
