# Generated by Django 3.2.9 on 2022-03-16 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0003_auto_20220224_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventories',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Cost Price'),
        ),
    ]
