# Generated by Django 3.2.9 on 2022-03-16 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0004_alter_inventories_cost_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truckexpense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
