# Generated by Django 3.2.9 on 2022-03-22 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0005_alter_truckexpense_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventories',
            name='created_at',
            field=models.DateField(verbose_name='Date'),
        ),
    ]
