# Generated by Django 3.2.9 on 2022-03-22 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0006_alter_inventories_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truckexpense',
            name='created_at',
            field=models.DateField(verbose_name='Date'),
        ),
    ]
