# Generated by Django 3.2.9 on 2022-03-20 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Expense', '0005_alter_expense_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['created_at']},
        ),
    ]
