# Generated by Django 3.2.9 on 2022-03-22 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expense', '0006_alter_expense_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensetype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='expensetype',
            name='created_at',
            field=models.DateField(verbose_name='Date'),
        ),
    ]
