# Generated by Django 3.2.9 on 2022-03-22 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expense', '0007_auto_20220322_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='created_at',
            field=models.DateField(verbose_name='Date'),
        ),
    ]
