# Generated by Django 3.2.9 on 2022-03-22 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salary', '0002_alter_salary_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='created_at',
            field=models.DateField(verbose_name='Date'),
        ),
    ]
