# Generated by Django 3.2.9 on 2022-01-24 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='clear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('agent_name', models.CharField(max_length=250)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=0, max_digits=10)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.inventories')),
            ],
        ),
    ]
