# Generated by Django 3.2.9 on 2022-01-08 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=7, verbose_name='Selling Price'),
        ),
    ]
