# Generated by Django 3.2.9 on 2022-03-22 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0005_alter_sale_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='created_at',
            field=models.DateField(verbose_name='Date'),
        ),
    ]
