# Generated by Django 3.2.9 on 2022-03-22 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0006_auto_20220322_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='balance',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
